# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3.1

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Create Builds for Testing
  #################
  - group: "🛠 Builds for Testing"
    steps:
      - label: "🛠 :jetpack: Build for Testing"
        key: "build_jetpack"
        command: ".buildkite/commands/build-for-testing.sh jetpack"
        env: *common_env
        plugins: *common_plugins
        notify:
          - github_commit_status:
              context: "Jetpack Build for Testing"
