# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.12.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.2

# This is the default pipeline – it will build and test the app
steps:

  #################
  # Build the app
  #################
  - label: "🛠 Build for Testing"
    key: "build"
    command: ".buildkite/commands/build-for-testing.sh"
    env: *common_env
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "Build for Testing"

  #################
  # UI Tests
  #################
  - group: "🔬 UI Tests"
    steps:
      - label: "🔬 UI Tests (iPhone)"
        command: .buildkite/commands/run-ui-tests.sh 'iPhone SE (3rd generation)'
        depends_on: "build"
        env: *common_env
        plugins: *common_plugins
        artifact_paths:
          - "build/results/*"
        notify:
          - github_commit_status:
              context: "UI Tests (iPhone)"
          - slack:
              channels:
                - "#mobile-apps-tests-notif"
            if: build.state == "failed" && build.branch == "trunk"
