# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-15.0.1

# This is the default pipeline – it will build and test the app
steps:
  - label: "🛠 :wordpress: Build for Testing - 14.3.1"
    key: "build_wordpress_14"
    command: ".buildkite/commands/build-for-testing.sh wordpress"
    env:
      IMAGE_ID: xcode-14.3.1
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "WordPress Build for Testing"

  - label: "🔬 :wordpress: Unit Tests - 14.3.1"
    command: ".buildkite/commands/run-unit-tests.sh"
    depends_on: "build_wordpress_14"
    env:
      IMAGE_ID: xcode-14.3.1
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"

  - label: "🛠 :wordpress: Build for Testing - 15.0.1"
    key: "build_wordpress"
    command: ".buildkite/commands/build-for-testing.sh wordpress"
    env: *common_env
    plugins: *common_plugins
    notify:
      - github_commit_status:
          context: "WordPress Build for Testing"

  - label: "🔬 :wordpress: Unit Tests - 15.0.1"
    command: ".buildkite/commands/run-unit-tests.sh"
    depends_on: "build_wordpress"
    env: *common_env
    plugins: *common_plugins
    artifact_paths:
      - "build/results/*"
    notify:
      - github_commit_status:
          context: "Unit Tests"
