# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.8.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: "a8c-repo-mirrors"
        repo: "wordpress-mobile/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14

steps:

  # Make sure there is a cached version of the pods avaialble before testing
  # the app or deploying installable builds to avoid parallel steps wasting
  # time building the same `Podfile.lock` from scratch.
  - label: ':cocoapods: Pre-load Pods'
    key: pods
    command: .buildkite/commands/load-pods.sh
    env: *common_env
    plugins: *common_plugins

  - label: ":wordpress: :testflight: WordPress Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-wordpress.sh $BETA_RELEASE"
    depends_on: "pods"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  - label: ":wordpress: :appcenter: WordPress Release Build (App Center)"
    command: ".buildkite/commands/release-build-wordpress-internal.sh"
    depends_on: "pods"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"

  - label: ":jetpack: :testflight: Jetpack Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build-jetpack.sh"
    depends_on: "pods"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
