common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
    - automattic/git-s3-cache#1.1.4:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/wordpress-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3.1

steps:
  - label: Test start code freeze
    command: |
      bundle install
      bundle exec fastlane run configure_apply
      bundle exec fastlane test_code_freeze_automation
    env: *common_env
    plugins: *common_plugins
